export interface EmailPayload {
  to: string;
  subject: string;
  html: string;
}

export async function sendEmail({ to, subject, html }: EmailPayload): Promise<boolean> {
  // In a real application, you would configure nodemailer or an API like Resend.
  // We provide a fully functioning structure that logs in development/fallback
  // and allows easy wiring to an environment variable-based client.

  console.log('==================================================');
  console.log(`SENDING EMAIL TO: ${to}`);
  console.log(`SUBJECT: ${subject}`);
  console.log('HTML CONTENT PREVIEW:');
  console.log(html.replace(/<[^>]*>/g, '').substring(0, 300) + '...');
  console.log('==================================================');

  // Example integration with Resend or NodeMailer (uncomment and install if needed):
  /*
  try {
    const response = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${process.env.RESEND_API_KEY}`,
      },
      body: JSON.stringify({
        from: 'Dental Clinic <appointments@yourclinic.com>',
        to,
        subject,
        html,
      }),
    });
    return response.ok;
  } catch (error) {
    console.error('Failed to send email via Resend API:', error);
    return false;
  }
  */

  return true;
}

export function generateAppointmentAdminEmailHtml(appointment: {
  name: string;
  email: string;
  phone: string;
  service: string;
  preferredDate: string;
  preferredTime: string;
  message?: string;
}) {
  return `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e2e8f0; border-radius: 8px;">
      <h2 style="color: #0f4c81; border-bottom: 2px solid #00a896; padding-bottom: 10px;">New Appointment Booking Request</h2>
      <p>A new appointment has been scheduled through the website clinic booking system.</p>
      <table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
        <tr style="background-color: #f8fafc;">
          <td style="padding: 10px; font-weight: bold; border: 1px solid #e2e8f0;">Full Name:</td>
          <td style="padding: 10px; border: 1px solid #e2e8f0;">${appointment.name}</td>
        </tr>
        <tr>
          <td style="padding: 10px; font-weight: bold; border: 1px solid #e2e8f0;">Email:</td>
          <td style="padding: 10px; border: 1px solid #e2e8f0;"><a href="mailto:${appointment.email}">${appointment.email}</a></td>
        </tr>
        <tr style="background-color: #f8fafc;">
          <td style="padding: 10px; font-weight: bold; border: 1px solid #e2e8f0;">Phone Number:</td>
          <td style="padding: 10px; border: 1px solid #e2e8f0;"><a href="tel:${appointment.phone}">${appointment.phone}</a></td>
        </tr>
        <tr>
          <td style="padding: 10px; font-weight: bold; border: 1px solid #e2e8f0;">Service Requested:</td>
          <td style="padding: 10px; border: 1px solid #e2e8f0;">${appointment.service}</td>
        </tr>
        <tr style="background-color: #f8fafc;">
          <td style="padding: 10px; font-weight: bold; border: 1px solid #e2e8f0;">Preferred Date:</td>
          <td style="padding: 10px; border: 1px solid #e2e8f0;">${appointment.preferredDate}</td>
        </tr>
        <tr>
          <td style="padding: 10px; font-weight: bold; border: 1px solid #e2e8f0;">Preferred Time:</td>
          <td style="padding: 10px; border: 1px solid #e2e8f0;">${appointment.preferredTime}</td>
        </tr>
        <tr style="background-color: #f8fafc;">
          <td style="padding: 10px; font-weight: bold; border: 1px solid #e2e8f0;">Patient Message:</td>
          <td style="padding: 10px; border: 1px solid #e2e8f0;">${appointment.message || 'No additional message.'}</td>
        </tr>
      </table>
      <div style="margin-top: 30px; text-align: center;">
        <p style="font-size: 12px; color: #64748b;">This email was automatically generated by the Dental Clinic booking system.</p>
      </div>
    </div>
  `;
}

export function generateAppointmentPatientEmailHtml(appointment: {
  name: string;
  service: string;
  preferredDate: string;
  preferredTime: string;
}) {
  return `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e2e8f0; border-radius: 8px;">
      <h2 style="color: #0f4c81; border-bottom: 2px solid #00a896; padding-bottom: 10px;">Appointment Received - Dental Clinic</h2>
      <p>Dear ${appointment.name},</p>
      <p>Thank you for requesting an appointment with us. We have received your booking request and will follow up shortly to confirm your scheduled slot.</p>
      <div style="background-color: #f0fdfa; padding: 15px; border-radius: 6px; margin: 20px 0; border: 1px solid #ccfbf1;">
        <h4 style="margin-top: 0; color: #0d9488;">Booking Summary:</h4>
        <ul style="list-style-type: none; padding-left: 0; margin-bottom: 0;">
          <li><strong>Service:</strong> ${appointment.service}</li>
          <li><strong>Date:</strong> ${appointment.preferredDate}</li>
          <li><strong>Preferred Time:</strong> ${appointment.preferredTime}</li>
        </ul>
      </div>
      <p>If you need to change or cancel your appointment, please contact us immediately at <a href="tel:+18005550199">+1 (800) 555-0199</a> or reply to this email.</p>
      <p>Best regards,</p>
      <p><strong>The Care Team</strong><br>Dental Clinic Group</p>
    </div>
  `;
}

export function generateContactAdminEmailHtml(contact: {
  name: string;
  email: string;
  phone: string;
  subject: string;
  message: string;
}) {
  return `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e2e8f0; border-radius: 8px;">
      <h2 style="color: #0f4c81; border-bottom: 2px solid #00a896; padding-bottom: 10px;">New Contact Form Inquiry</h2>
      <p>A message has been submitted from the clinic website contact form.</p>
      <table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
        <tr style="background-color: #f8fafc;">
          <td style="padding: 10px; font-weight: bold; border: 1px solid #e2e8f0;">Full Name:</td>
          <td style="padding: 10px; border: 1px solid #e2e8f0;">${contact.name}</td>
        </tr>
        <tr>
          <td style="padding: 10px; font-weight: bold; border: 1px solid #e2e8f0;">Email:</td>
          <td style="padding: 10px; border: 1px solid #e2e8f0;"><a href="mailto:${contact.email}">${contact.email}</a></td>
        </tr>
        <tr style="background-color: #f8fafc;">
          <td style="padding: 10px; font-weight: bold; border: 1px solid #e2e8f0;">Phone:</td>
          <td style="padding: 10px; border: 1px solid #e2e8f0;"><a href="tel:${contact.phone}">${contact.phone}</a></td>
        </tr>
        <tr>
          <td style="padding: 10px; font-weight: bold; border: 1px solid #e2e8f0;">Subject:</td>
          <td style="padding: 10px; border: 1px solid #e2e8f0;">${contact.subject}</td>
        </tr>
        <tr style="background-color: #f8fafc;">
          <td style="padding: 10px; font-weight: bold; border: 1px solid #e2e8f0;">Message:</td>
          <td style="padding: 10px; border: 1px solid #e2e8f0;">${contact.message}</td>
        </tr>
      </table>
    </div>
  `;
}
